[package]
name = "symbolic-minidump"
version = "5.0.1"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-minidump"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library to process and inspect Minidump crash reports
"""
build = "build.rs"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
gimli = "0.15.0"
lazy_static = "1.0.0"
regex = "0.2.10"
serde = { version = "1.0.42", optional = true }
serde_plain = { version = "0.3.0", optional = true }
symbolic-common = { version = "5.0.1", path = "../common" }
symbolic-debuginfo = { version = "5.0.1", path = "../debuginfo" }
uuid = "0.6.3"

[build-dependencies]
cc = { version = "1.0.10", features = ["parallel"] }

[dev-dependencies]
symbolic-testutils = { version = "5.0.1", path = "../testutils" }

[features]
default = []
with_serde = ["serde", "serde_plain"]
