[package]
name = "object_debug"
version = "10.1.3"
authors = ["Jan Michael Auer <mail@jauer.org>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.0"
symbolic = { path = "../../symbolic" }
