[package]
name = "symbolic-proguard"
version = "2.0.2"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-proguard"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library to process ProGuard mapping files and symbolicate frames from
optimized applications.
"""

[dependencies]
symbolic-common = { version = "2.0.2", path = "../common" }
proguard = "1.0.0"
uuid = "0"
