[package]
name = "symbolic-symcache"
version = "5.1.2"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-symcache"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
An optimizied cache file for fast and memory efficient lookup of symbols and
stack frames in debugging information.
"""

[dependencies]
dmsort = "0.1.3"
failure = "0.1.1"
failure_derive = "0.1.1"
fallible-iterator = "0.1.4"
fnv = "1.0.6"
gimli = "0.15.0"
if_chain = "0.1.2"
lru-cache = "0.1.1"
matches = "0.1.6"
num = "0.1.42"
symbolic-common = { version = "5.1.2", path = "../common", features = ["with_dwarf", "with_objects"] }
symbolic-debuginfo = { version = "5.1.2", path = "../debuginfo" }
symbolic-demangle = { version = "5.1.2", path = "../demangle" }
uuid = { version = "0.6.3", features = ["serde"] }

[dev-dependencies]
symbolic-testutils = { version = "5.1.2", path = "../testutils" }
